### PR TITLE
Add a Makefile

### PR DESCRIPTION
**Pull request by Vandit1604**

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Vandit1604 Could you please add instructions to the [README.md]() on how to use the `Makefile`?

I am getting an error if I just run `make` out-of-the-box BTW, what do I need to do before I can run it without any issues?:
```bash
krisstern@Kris-Sterns-Air jenkins-docs % make
Building UI
cd ./ui && gulp bundle
/bin/sh: gulp: command not found
make: *** [ui] Error 127
```

There seems to be a lot you are not communiating to the user that is either assumed or neglected, and will need to be fixed.

**Review by krisstern — CHANGES_REQUESTED** [review]
I cannot run the part of the code related to `antora` even though I have `@antora/site-generator` globally installed:
```
cd ./playbook && npx antora antora-playbook.yml --stacktrace --fetch
[21:22:42.321] FATAL (antora): Generator not found or failed to load. Try installing the '@antora/site-generator' package.
    Cause: Error: Cannot find module '@antora/site-generator' at path /Users/krisstern/jenkins-docs/playbook or /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/lib
    Require stack:
    - /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/@antora/user-require-helper/lib/index.js
    - /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/lib/cli.js
    - /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/lib/index.js
    - /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/bin/antora
        at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
        at resolve (node:internal/modules/cjs/helpers:127:19)
        at userRequire.resolve (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/@antora/user-require-helper/lib/index.js:81:12)
        at Command.<anonymous> (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/lib/cli.js:136:62)
        at Command.listener [as _actionHandler] (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:488:17)
        at /Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:1227:65
        at Command._chainOrCall (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:1144:12)
        at Command._parseCommand (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:1227:27)
        at Command._dispatchSubcommand (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:1050:25)
        at Command._parseCommand (/Users/krisstern/.nvm/versions/node/v18.17.1/lib/node_modules/@antora/cli/node_modules/commander/lib/command.js:1203:19)
make: *** [antora] Error 1
```

This still needs work for the `Makefile` to work for a new user.

**Comment by krisstern** [comment]
Also, you should not put the label `hacktoberfest-accepted` on your PR unless your PR has indeed been flavorably reviewed by someone else. Otherwise it is not a fair practice. You should never evaluate your own PR's favorably without someone with a more objective angle can review it.

**Comment by Vandit1604** [comment]
> Also, you should not put the label `hacktoberfest-accepted` on your PR unless your PR has indeed been flavorably reviewed by someone else. Otherwise it is not a fair practice. You should never evaluate your own PR's favorably without someone with a more objective angle can review it.

Sorry I thought you can do that. I have removed the label

**Comment by Vandit1604** [comment]
Yep as you have done. only the npm dependencies were left out intentionally from the Makefile because I thought Antora and Gatsby should be in the README.md as prerequisites.

**Comment by krisstern** [comment]
> @krisstern Should I add things you have to be installed before running the `make` command in the README.md

@Vandit1604 More like you are missing some important commands in the `Makefile`

**Comment by Vandit1604** [comment]
@krisstern I would suggest we do this

> Antora and Gatsby should be in the README.md as prerequisites.

Because if a new version is rolled out from Antora and Gatsby `npm i` will update the dependencies automatically.

**Comment by krisstern** [comment]
> Yep as you have done. only the npm dependencies were left out intentionally from the Makefile because I thought Antora and Gatsby should be in the README.md as prerequisites.

That defeats the purpose of the `Makefile`, which is to automate the entire development process.

**Comment by Vandit1604** [comment]
> That defeats the purpose of the Makefile, which is to automate the entire development process.

Alright I thought we are only using Makefile for building the new site but if it's automating and make it easy to set up the project then it should have `npm i` in the Makefile.

**Comment by Vandit1604** [comment]
> Do you mean we should install specific versions of the packages? If so, please do so with the package.json files to fix the versions.

Just checked the `package.json` files of antora work with specific versions and that is already fixed so we don't have to do anything

**Comment by krisstern** [comment]
Hi @Vandit1604 I think we will have to use `docker` to host our Antora `docs` at least (right not it is not hosted at all), so the `Makefile` will be a lot more like the one in use for jenkins.io at https://github.com/jenkins-infra/jenkins.io/blob/master/Makefile. Could you think about ways to improve it and actually have a hosted "live" site instead of just some static pages?

**Comment by krisstern** [comment]
I will add the `hacktoberfest-accepted` label for this PR for you once it is ready to be merged.

**Comment by krisstern** [comment]
Some good reference for us: https://docs.antora.org/antora/latest/antora-container/

**Comment by krisstern** [comment]
> > Hi @Vandit1604 I think we will have to use `docker` to host our Antora `docs` at least (right not it is not hosted at all), so the `Makefile` will be a lot more like the one in use for jenkins.io at https://github.com/jenkins-infra/jenkins.io/blob/master/Makefile. Could you think about ways to improve it and actually have a hosted "live" site instead of just some static pages?
> 
> Do you mean we host the pages in docker ?

More like we deploy a static website to the container.

**Comment by Vandit1604** [comment]
For local development right as of now it can be seen by typing the file path given by antora when we run `make` command.

**Comment by krisstern** [comment]
> For local development right? because as of now it can be seen by typing the file path given by antora when we run `make` command.

We want a development flow that micmicks the current jenkins.io development flow.

**Comment by krisstern** [comment]
If it is too much work for you I can do thts later. Currently there is not much benefit with the `Makefile` in its current state.

**Comment by krisstern** [comment]
We want to use a `Makefile` to host both the Antora `docs` site and Gatsby `blog` on the localhost, not as a static site, so it will take some thought to figure out how to do so. I can work with the infra team on this. For now please focus on generating a funtional Antora `docs` site and Gatsby `blog`, or we will never be able finish the work.

**Comment by Vandit1604** [comment]
> If it is too much work for you I can do thts later. Currently there is not much benefit with the `Makefile` in its current state. 

If this needs to be done till the end of next week. I would like to try working on this.

**Comment by krisstern** [comment]
Okay, sure

**Comment by Vandit1604** [comment]
> We want to use a `Makefile` to host both the Antora `docs` site and Gatsby `blog` on the localhost, not as a static site, so it will take some thought to figure out how to do so. I can work with the infra team on this. For now please focus on generating a funtional Antora `docs` site and Gatsby `blog`, or we will never be able finish the work. 

If that's the case so I would focus on completing the blog and doc first and then focus on other things.

**Pull request closed without merging**
