### PR TITLE
Solve Antora Build Error Logs

### PR DESCRIPTION
**Pull request by Vandit1604**
- [ ] @krisstern The errors that still persist are either coming from `/advisory/` or from pages where i can't find the link even after find searching it. Could you please take a look on the logs that we see now.

### CODE REVIEW

**Comment by krisstern** [comment]
@Vandit1604 Did you check if the links work?

**Comment by krisstern** [comment]
> @krisstern The errors that still persist are either coming from `/advisory/` or from pages where i can't find the link even after find searching it. Could you please take a look on the logs that we see now.

I don't think I saw what you are referring to here.

**Comment by krisstern** [comment]
> > @Vandit1604 Did you check if the links work?
> 
> Yeah most of them work. it's the links with fragments to a specific section that don't work. These type of errors will need to be reported by the users because we can't check all of them if antora doesn't even report them.
> 
> Although The number of these type of links is relatively less.

@Vandit1604 I do not think that is acceptable, which means that we will likely need to postpone hosting of the versioned docs site before we conduct a more thorough check of each component.

**Comment by Vandit1604** [comment]
Links that are like this `<<fragment-name,Link text>>` are the problematic ones.They are around 156 links. I have started fixing them. 
Since it's the weekend. If you give me all the things that need to be fixed. I can pull them off till monday.

**Comment by krisstern** [comment]
> Links that are like this `<<fragment-name,Link text>>` are the problematic ones.They are around 156 links. I have started fixing them. Since it's the weekend. If you give me all the things that need to be fixed. I can pull them off till monday.

Yeah, I think I have fixed a small portion of these already. Sure, this is not a critical mission so we can wait for a few more days.

**Comment by krisstern** [comment]
I am fixing the advisories now actually

**Comment by krisstern** [comment]
Maybe you can check the other areas so that our effort is not duplicated @Vandit1604

**Comment by Vandit1604** [comment]
> Maybe you can check the other areas so that our effort is not duplicated @Vandit1604 

Works for me. I'm out currently if you raise a PR I'll push my commits on it.

**Comment by krisstern** [comment]
Just don't push anything to it I will raise a PR and you can check first and raise another PR to add to the repo.

**Comment by krisstern** [comment]
Also @Vandit1604 We have some issues opened by Kevin, you may want to address them one-by-one.

**Pull request merged**
