### PR TITLE
fix: Add Opengraph Images to each Blogpost

### PR DESCRIPTION
**Pull request by Vandit1604**

### CODE REVIEW

**Review by iamrajiv — APPROVED** [review]

**Comment by krisstern** [comment]
Hi @Vandit1604 Thanks for the PR! Just curious to know why are there all these changes to the relative position of the `description`'s in their respective `blog/content` directories?

**Comment by Vandit1604** [comment]
Hi @krisstern I did that to give a sense of uniformity in each adoc page. Also I'm thinking of removing the description or converting it into :page-description: to create a pageAttribute.

**Comment by krisstern** [comment]
Sure, that makes sense to me. I see the `opengraph` values in the `page-data.json` files are currently all `null`. Is there any reason why this is so?

**Comment by Vandit1604** [comment]
It's not null everywhere. I can guess that older blogposts didn't contain opengraph image in them. that's why it's null for them. we have opengraph value for page 2023 asciidoc pages

**Comment by krisstern** [comment]
Cool, then I would suggest setting a dummy opengraph image for the ones with either `null` or `""` or any falsy values for the `opengraph` variable.

**Comment by Vandit1604** [comment]
I have tried 

1. Pasting the image in the same folder. it was still not working
2. Pasting the image name directory i.e the path of opengraph image it was still not working.
3. tried changing the `imagesdir` attribute in gatsby-config.js didn't work. 

But I got to know that we would have to fix all the relative paths in asciidoc images because It is not recommended. [See here](https://www.gatsbyjs.com/plugins/gatsby-transformer-asciidoc/#set-imagesdir)

**Comment by Vandit1604** [comment]
In Jenkins we started adding opengraph image after 19 Feb 2020 i.e from this post onwards `blog/content/2020/02/2020-02-19-jenkins-world-lisbon-with-love-from-india.adoc` 
Now, I'm checking again if post from this onwards have the correct value or its still `null`

**Comment by krisstern** [comment]
In React you have to either import the image as a variable via the import statement above, or use the `require()` method for the `src` of an `img` tag. Note usually the `img` tag is self closing. I have made the change via a new commit, but it is now complaining that "Uncaught Error: Cannot find module '/images/gsoc/:page-opengraph.png'", I will let you fix this.

**Comment by krisstern** [comment]
It this trick still does not work to show the opengraph images we will need to try and use the `.default` property, as in the following inside the `img` tag:
```javascript
src={require(node.pageAttributes.opengraph).default}
```

**Review by krisstern — APPROVED** [review]
The `opengraph` feature still needs finetuning, but at least we can show a dummy image in its place now for styling purposes.

**Pull request merged**
