### PR TITLE
feat: Add some styling using .css.modules

### PR DESCRIPTION
**Pull request by Vandit1604**
I'll use styled components but this helped in creating a structure when i'll use and fixed some things that got messed up.

### CODE REVIEW

**Comment by Vandit1604** [comment]
@krisstern Should I add the public/ folder into `.gitignore` ?
Let me check in Gatsby Docs its usage.

**Comment by krisstern** [comment]
Yes, we should follow this .gitignore for `gatsby`: https://github.com/gatsbyjs/gatsby/blob/master/.gitignore

**Comment by Vandit1604** [comment]
@krisstern Done

**Comment by krisstern** [comment]
I think we should keep the `blog/package-lock.json` file committed.

**Comment by krisstern** [comment]
Would you like to add that? @Vandit1604

**Comment by krisstern** [comment]
Or let me add it back to the `.gitignore` file for sticking with the recommendations.

**Comment by krisstern** [comment]
So essentially we want to keep the `package-lock.json` at root but ignore the `blog/package-lock.json` file.

**Review by krisstern — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Comment by Vandit1604** [comment]
Styling looks good.

**Pull request merged**
