### PR TITLE
fix: Tweaked Styling of Index Page

### PR DESCRIPTION
**Pull request by Vandit1604**

### CODE REVIEW

**Comment by Vandit1604** [comment]
Now the blogs are in an ordered fashion [latest to oldest]

**Review by iamrajiv — APPROVED** [review]

**Comment by krisstern** [comment]
I think we could add zoom on Hover effect for the opengraph images on the blog's homepage too

**Comment by Vandit1604** [comment]
@krisstern Done

**Review by iamrajiv — APPROVED** [review]

**Review by krisstern — APPROVED** [review]
LGTM. Great work!

**Pull request merged**
