### PR TITLE
Complete Adopters Page

### PR DESCRIPTION
**Pull request by Vandit1604**
If there's any UI/UX improvements do suggest me.

### CODE REVIEW

**Comment by Vandit1604** [comment]
If we want to have the table-like structure for the adopters. Do let me know. I went with the artwork page UI to maintain uniformity.

**Comment by krisstern** [comment]
Where are the images?

**Comment by Vandit1604** [comment]
@krisstern Fixed the images.

**Review by krisstern — APPROVED** [review]

**Comment by Vandit1604** [comment]
LGTM 🚀

**Pull request merged**
