### PR TITLE
Implement pipeline and upgrade guides

### PR DESCRIPTION
**Pull request by Vandit1604**
Implement pipeline reference and upgrade guide

Currently, the pipeline reference headings are not available on `/pipeline-reference` like we have on https://www.jenkins.io/doc/pipeline/steps/ and upgrade guide pages for different versions are not a single page but coming as different pages. What I mean is https://www.jenkins.io/doc/upgrade-guide/2.426/#upgrading-to-jenkins-lts-2-426-3 and https://www.jenkins.io/doc/upgrade-guide/2.426/#upgrading-to-jenkins-lts-2-426-1 are heading of a single page, but we have them as different page in our setup.

I'll implement the left out features in another PR both for pipeline reference and upgrade guide.

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Vandit1604 I think there are too many file changes in a single PR. Next time maybe better to split this into different PRs. Otherwise the GitHub UI freezes when I tried to review your code.

**Comment by krisstern** [comment]
I am seeing this in the console while running the development version of the app:
```shell
warn The GraphQL query in the non-page component "/Users/krisstern/jenkins-docs/site/src/templates/upgrade-guide-template.js" will not be run.
Exported queries are only executed for page components. It's possible you're trying to create pages in your gatsby-node.js and that's failing for some reason.

If the failing component is a regular component and not intended to be a page component, you generally want to use "useStaticQuery"
(https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/) instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL fragments from components and compose the fragments in the Page component query and pass data
down into the child component (https://www.gatsbyjs.com/docs/reference/graphql-data-layer/using-graphql-fragments/)
```

I think you better look into it to see if it necessitates code change or is just false alarm.

**Comment by krisstern** [comment]
This ordering is not acceptable, you will need to find a way to order everything properly as versions go:

Screenshot 2024-04-22 at 7 27 21 PM

The ordering should be from the latest version to the oldest.

**Comment by krisstern** [comment]
Also, try to do what they do here: https://www.jenkins.io/doc/upgrade-guide/

**Comment by krisstern** [comment]
I am seeing the developer guide landing page as broken right now:

Screenshot 2024-04-22 at 7 30 49 PM

**Comment by krisstern** [comment]
Also, for http://localhost:8000/doc/pipeline/steps it is broken now. You could redirect to /pipeline-reference, or reconfigure the setup. As discussed previously you are not supposed to change the paths of the pages. So please make a correction for this:

Screenshot 2024-04-22 at 7 32 46 PM

**Comment by krisstern** [comment]
In fact the docs page links are all broken now if I use the navigation bar up top. Would you like to investigate and fix?

**Comment by krisstern** [comment]
My apologies @Vandit1604 I just realised we don't have a good way to map the docs now since the site has not yet been launched. But could you think of a better way to handle this, since the pipeline steps should be in docs?

**Comment by Vandit1604** [comment]
Should I try redirection with https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/

I'll raise another PR for that since this one is quite big.

**Comment by Vandit1604** [comment]
> But could you think of a better way to handle this, since the pipeline steps should be in docs?

We can set up a redirect from the doc site to the Gatsby site. While adding redirections for backward compatibility.

**Comment by krisstern** [comment]
> Should I try redirection with https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/
> 
> I'll raise another PR for that since this one is quite big.

I think so, we should definitely try redirecting in a. systematic and well-planned way. 
Sure, will wait for your other PR.

**Comment by krisstern** [comment]
> > But could you think of a better way to handle this, since the pipeline steps should be in docs?
> 
> We can set up a redirect from the doc site to the Gatsby site. While adding redirections for backward compatibility.

Yeah, sounds good!

**Review by krisstern — APPROVED** [review]
LGTM

**Pull request merged**
