### PR TITLE
Add Jenkins download sources table in download page

### PR DESCRIPTION
**Pull request by Vandit1604**
Couldn't find the same icon so used another icon which i got after searching for Library

### CODE REVIEW

**Review by krisstern — APPROVED** [review]
LGTM, but do we have plans to add the value for the `SHA-256` on the download page?

**Comment by Vandit1604** [comment]
> LGTM, but do we have plans to add the value for the `SHA-256` on the download page?

Absolutely @krisstern  but I was thinking if I could day it later after we get done with the blogs if that's okay.

**Comment by krisstern** [comment]
Sure, but do note this in a `TODO` list for better project management

**Comment by Vandit1604** [comment]
Like you said for better project management and we don't forget something. Let me add this in the meeting minutes doc.

**Pull request merged**
