### PR TITLE
Updating card logic and add authors page

### PR DESCRIPTION
**Pull request by Vandit1604**

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Vandit1604 I can only see the Author's names on the homepage but not the blog post article names in the PR. What is this PR for exactly? Looks like it still need some work.

**Comment by krisstern** [comment]
The Authors page looks good though.

**Comment by Vandit1604** [comment]
@krisstern If you scroll down you would see the blogs too. We need to show cards only that dont have `node.document.title == "Author"` and opposite of that for author's page.

**Comment by krisstern** [comment]
But we do not want to show the Authors detail on the homepage. Could you make a change to this before this PR can be merged?

**Comment by Vandit1604** [comment]
Yeah, I'm working on it right now.

**Comment by Vandit1604** [comment]
> But we do not want to show the Authors detail on the homepage. Could you make a change to this before this PR can be merged?

Fixed it.

**Comment by krisstern** [comment]
The `/authors` page looks okay except it needs a bit of work on the styling.

**Comment by Vandit1604** [comment]
reference links need to be fixed still working on that.

**Pull request merged**
