### PR TITLE
fix: patch reference, issues, pull links that were not showing

### PR DESCRIPTION
**Pull request by Vandit1604**
Earlier the reference, issues and PR links were not visible in LTS and Weekly Changelogs. This PR fixes them.

### CODE REVIEW

**Comment by krisstern** [comment]
Please pause all PRs for this repo as discussed on Gitter previously. We will be moving to one under jenkins-infra soon.

**Comment by krisstern** [comment]
Thanks, I will review this later today

**Comment by krisstern** [comment]
I am wondering if this formatting is intentional? It looks like more work is needed to get this right. 

Screenshot 2024-01-04 at 7 42 00 PM

**Comment by Vandit1604** [comment]
Tonight (IST), I can figure out something to link respective authors to the authors page.

**Review by krisstern — APPROVED** [review]
LGTM

**Pull request merged**
